version: '3.7'
services:
  web:
    build: .
    ports:
      - "3030:3030"
    # links:
    #   - mongodb
    depends_on:
      - mongodb
    # environment:
    #   API_HOST: http://localhost:3030/
    #   APP_SERVER_PORT: 3030
  # frontend:
  #   image: frontend:latest
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - mongodb
  #     - web
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
      - mongoconfig:/data/configdb

volumes:
  mongodata:
    # if you want to connect to existing database instead of create new one?
    # external: true
  mongoconfig:
    # external: true
